# version: '3.8'

# services:
#   mysql:
#     image: mysql:8.0
#     container_name: mysql-db
#     environment:
#       MYSQL_ROOT_PASSWORD: user123
#       MYSQL_DATABASE: mentormate
#     ports:
#       - "3307:3306"
#     volumes:
#       - mysql-data:/var/lib/mysql

#   app:
#     build: .
#     image: mentor-mate:latest
#     container_name: mentor-mate-app
#     ports:
#       - "8080:8080"
#     environment:
#       SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3307/mentormate
#       SPRING_DATASOURCE_USERNAME: root
#       SPRING_DATASOURCE_PASSWORD: user123
#     depends_on:
#       - mysql

# volumes:
#   mysql-data:


version: '3.8'

services:
  server:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
  mysqldb:
    image: "mysql:8.1"
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: mentormate
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password