version: '3.8'

services:
  server:
    build: .
    image: mentormate:webapp
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mentormate?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false

      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: mentormate.help@gmail.com
      SPRING_MAIL_PASSWORD: ntkqaepvkunnhrht
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"
      SPRING_FLYWAY_URL: jdbc:mysql://mysql:3306/mentormate?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_FLYWAY_USER: admin
      SPRING_FLYWAY_PASSWORD: password
      SPRING_FLYWAY_LOCATIONS: classpath:db/migration
      SPRING_FLYWAY_BASELINE_ON_MIGRATE: "true"
    depends_on:
      mysql:
        condition: service_healthy
    
  mysql:
    image: "mysql:8.1"
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: mentormate
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
 
