apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  replicas: 2  # Adjust as needed
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: 122238031788.dkr.ecr.ap-south-1.amazonaws.com/mentormate:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: webapp-persistent-storage
              mountPath: /app/data
      volumes:
        - name: webapp-persistent-storage
          persistentVolumeClaim:
            claimName: webapp-pv-claim
