apiVersion: v1
kind: PersistentVolume
metadata:
  name: webapp-pv-volume
spec:
  capacity:
    storage: 1Gi  
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual  
  hostPath:
    path: "/mnt/data/webapp"  

